name: CI/CD Pipeline

on:
  push:
    branches:
      - feature-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t akshaygaikwad009/best_bus_backend:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push akshaygaikwad009/best_bus_backend:latest

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull akshaygaikwad009/best_bus_backend:latest
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true
            docker run -d -p 80:4000 akshaygaikwad009/best_bus_backend:latest
